framework:
    http_method_override: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    cors:
        defaults:
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
